site_name: ODEPINNSFramework
site_description: ODEPINNSFramework is a Python framework for simulating and solving Ordinary Differential Equations (ODEs) using Physics-Informed Neural Networks (PINNs). It combines data-driven learning with physical constraints, enabling models to learn solutions that respect underlying dynamical systems. The framework is designed to be modular, flexible, and suitable for both research and practical applications.

theme:
  name: material          # pip install mkdocs-material
  
nav:
  - Home: index.md
  - Code: code.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - admonition
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

