site_name: ODEPINNSFramework
site_description: ODEPINNSFramework is a Python framework for simulating and solving Ordinary Differential Equations (ODEs) using Physics-Informed Neural Networks (PINNs). It combines data-driven learning with physical constraints, enabling models to learn solutions that respect underlying dynamical systems. The framework is designed to be modular, flexible, and suitable for both research and practical applications.
site_url: https://frobinou.github.io/PINNSFramework/
repo_url: https://github.com/Frobinou/PINNSFramework
repo_name: Frobinou/PINNSFramework

nav:
  - Accueil: index.md
  # Ajoutez vos pages ici

plugins:
  - search
  - minify:
      minify_html: true

theme:
  name: material          # pip install mkdocs-material
  language: en
  font:
    text: Raleway        # police du corps
    code: Source Code Pro  # police du code
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

nav:
  - Home: index.md
  - Code: code.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
  - search
  - i18n:
      default_language: en
      languages:
        - locale: fr
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          default: true
extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr
    - name: English
      link: /
      lang: en

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - admonition
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

